name: Terraform Validation

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  terraform-validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5  # Specify your version

      - name: Validate Terraform-01
        run: |
          cd terraform-01
          terraform init -backend=false
          terraform validate

      - name: Validate Terraform-02 Dev
        run: |
          cd terraform-02/clusters/dev
          terraform init -backend=false
          terraform validate

      - name: Validate Terraform-02 Test
        run: |
          cd terraform-02/clusters/test
          terraform init -backend=false
          terraform validate
          
      - name: Validate Terraform-02 Prod
        run: |
          cd terraform-02/clusters/prod
          terraform init -backend=false
          terraform validate

      - name: Terraform Format Check
        run: |
          find . -name "*.tf" -type f -exec echo "Checking format for: {}" \; -exec terraform fmt -check {} \;
